# Generated by Django 4.2.7 on 2025-08-22 14:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(choices=[('dni', 'DNI'), ('pasaporte', 'Pasaporte'), ('ruc', 'RUC'), ('ce', 'Carné de Extranjería')], default='dni', max_length=20, verbose_name='Tipo de Identificación')),
                ('numero_identificacion', models.CharField(max_length=20, unique=True, verbose_name='Número de Identificación')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('lugar_nacimiento', models.CharField(max_length=100, verbose_name='Lugar de Nacimiento')),
                ('estado_civil', models.CharField(choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a'), ('union_libre', 'Unión Libre')], max_length=20, verbose_name='Estado Civil')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('ocupacion', models.CharField(max_length=100, verbose_name='Ocupación')),
                ('lugar_trabajo', models.CharField(max_length=200, verbose_name='Lugar de Trabajo')),
                ('ingreso_mensual', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ingreso Mensual')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='ReferenciaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('parentesco', models.CharField(max_length=50, verbose_name='Parentesco')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias_personales', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Referencia Personal',
                'verbose_name_plural': 'Referencias Personales',
            },
        ),
        migrations.CreateModel(
            name='DocumentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('dni_frente', 'DNI (Frente)'), ('dni_dorso', 'DNI (Dorso)'), ('recibo_servicio', 'Recibo de Servicio'), ('recibo_sueldo', 'Recibo de Sueldo'), ('otro', 'Otro Documento')], max_length=20, verbose_name='Tipo de Documento')),
                ('archivo', models.FileField(upload_to='clientes/documentos/', verbose_name='Archivo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Documento de Cliente',
                'verbose_name_plural': 'Documentos de Clientes',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
