# Generated by Django 4.2.7 on 2025-08-22 14:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_credito', models.CharField(choices=[('PER', 'Personal'), ('HIP', 'Hipotecario'), ('AUT', 'Automotriz'), ('EDU', 'Educativo'), ('OTR', 'Otro')], default='PER', max_length=3, verbose_name='Tipo de Crédito')),
                ('monto_solicitado', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Solicitado')),
                ('plazo_meses', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(360)], verbose_name='Plazo en Meses')),
                ('tasa_interes', models.DecimalField(decimal_places=2, help_text='Tasa de interés anual en porcentaje (ej: 15.5)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tasa de Interés Anual')),
                ('puntaje_credito', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='Puntaje de Crédito')),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('APR', 'Aprobado'), ('REC', 'Rechazado'), ('ESP', 'En espera'), ('CAN', 'Cancelado')], default='PEN', max_length=3, verbose_name='Estado')),
                ('ingresos_mensuales', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ingresos Mensuales')),
                ('gastos_mensuales', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gastos Mensuales')),
                ('deuda_actual', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Deuda Actual')),
                ('historial_crediticio', models.TextField(blank=True, help_text='Resumen del historial crediticio del cliente', verbose_name='Historial Crediticio')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre el análisis', verbose_name='Observaciones')),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Análisis')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_creditos', to='clientes.cliente', verbose_name='Cliente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analisis_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Analista')),
            ],
            options={
                'verbose_name': 'Análisis de Crédito',
                'verbose_name_plural': 'Análisis de Créditos',
                'ordering': ['-fecha_analisis'],
                'permissions': [('can_approve_credit', 'Puede aprobar créditos'), ('can_reject_credit', 'Puede rechazar créditos')],
            },
        ),
        migrations.CreateModel(
            name='DocumentoAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('IDE', 'Identificación'), ('ING', 'Comprobante de Ingresos'), ('RB', 'Referencia Bancaria'), ('RC', 'Referencia Comercial'), ('OTR', 'Otro')], default='OTR', max_length=3, verbose_name='Tipo de Documento')),
                ('archivo', models.FileField(upload_to='creditos/documentos/%Y/%m/%d/', verbose_name='Archivo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='creditos.analisiscredito', verbose_name='Análisis de Crédito')),
            ],
            options={
                'verbose_name': 'Documento de Análisis',
                'verbose_name_plural': 'Documentos de Análisis',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
